### ISSUE TITLE
Add proper comments for documentation purpose

### ISSUE THREAD

**Issue by akhilrao2797** [akhilrao2797/RentMe-Vehicle#15]
Comments for all the services and utils.

**Comment by nhimanshujain** [comment]
Hi @akhilrao2797 Can you assign this issue to me. Thanks.

**Comment by akhilrao2797** [comment]
Sure @nhimanshujain . Please let me know if you need any help

**Comment by nhimanshujain** [comment]
@akhilrao2797 Created PR #31 . Please Review and Close the issue. Thanks from India!!

**Comment by akhilrao2797** [comment]
Merged #31 .
Thanks @nhimanshujain .
