### ISSUE TITLE
Add authorization for admin

### ISSUE THREAD

**Issue by akhilrao2797** [akhilrao2797/RentMe-Vehicle#23]
* Spring security with roles

**Comment by ashwinpadmakumar** [comment]
@akhilrao2797 Since this is a bit correlated with #22 will try to do this also.

**Comment by akhilrao2797** [comment]
sure @ashwinpadmakumar . assigned it to you.

**Comment by akhilrao2797** [comment]
merged in #30 .
Thanks @ashwinpadmakumar
