### ISSUE TITLE
Add a vehicle image in readme

### ISSUE THREAD

**Issue by akhilrao2797** [akhilrao2797/RentMe-Vehicle#40]

**Comment by frantic-rabbit** [comment]
Hey! Assign it to me.

**Comment by cyberdad68** [comment]
i would like to work on this issue,Could you assign me this.

**Comment by akhilrao2797** [comment]
@frantic-rabbit assigned it to you

**Comment by frantic-rabbit** [comment]
> @frantic-rabbit assigned it to you

@akhilrao2797 Which vehicle image do you want to be added i readme?

**Comment by Alekia** [comment]
please assign this to me
